//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscadoDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mercado_has_Produto_has_Setor
    {
        public Nullable<int> idSetor { get; set; }
        public Nullable<int> idMercado_has_Produto { get; set; }
        public int idMercado_has_Produto_has_Setor { get; set; }
    
        public virtual Mercado_has_Produto Mercado_has_Produto { get; set; }
        public virtual Setor Setor { get; set; }
    }
}
