//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscadoDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mercado_has_Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mercado_has_Produto()
        {
            this.Mercado_has_Produto_has_Setor = new HashSet<Mercado_has_Produto_has_Setor>();
            this.Oferta = new HashSet<Oferta>();
        }
    
        public int idMercado_has_Produto { get; set; }
        public Nullable<int> idProduto { get; set; }
        public Nullable<int> idMercado { get; set; }
        public decimal Preco { get; set; }
        public string Corredor { get; set; }
    
        public virtual Mercado Mercado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mercado_has_Produto_has_Setor> Mercado_has_Produto_has_Setor { get; set; }
        public virtual Produto Produto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oferta> Oferta { get; set; }
    }
}
