//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuscadoDesktop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BuscadoEntities : DbContext
    {
        public BuscadoEntities()
            : base("name=BuscadoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administrador { get; set; }
        public virtual DbSet<Email> Email { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Mercado> Mercado { get; set; }
        public virtual DbSet<Mercado_has_Produto> Mercado_has_Produto { get; set; }
        public virtual DbSet<Mercado_has_Produto_has_Setor> Mercado_has_Produto_has_Setor { get; set; }
        public virtual DbSet<Oferta> Oferta { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<Setor> Setor { get; set; }
        public virtual DbSet<Telefone> Telefone { get; set; }
    }
}
